### ISSUE TITLE
"Fragrant" Pheromone Fish - used but nothing happens 

### ISSUE THREAD

**Issue by fishea** [unknowndev/CoolFish#31]
Hi,

maybee a bug. i got a few Pheromone Fish. 

they were in my inventory and used before the bot fished again.
happened at least 6 times. its only usable on friends but i think most of us are fishing alone.
could be the bot think its a buff for yourself.

**Comment by unknowndev** [comment]
Resolving this issue as wontfix as I don't think I will put this feature in the base CoolFish bot. I think this belongs in a plugin or bot base.
