### ISSUE TITLE
Use any bait

### ISSUE THREAD

**Issue by aoxfordca** [unknowndev/CoolFish#33]
Would love to be able to have the option to use any bait that is available. Useful for garrisons where baits don't drop as often.

**Comment by GliderPro** [comment]
I have a pull request with changes to apply the first bait found in your bags. It's nothing fancy but it let's me fire off the bot for an hour in my garrison and minimize the amount of Crescent Saberfish I catch. A priority list or some randomization would be better.

https://github.com/unknowndev/CoolFish/pull/44

**Comment by unknowndev** [comment]
I'll try to take a look at the pull request today. Thanks for your work
