### ISSUE TITLE
Add Nat Pagel's Hat and Fishing Pole

### ISSUE THREAD

**Issue by SkyeHeart29** [unknowndev/CoolFish#49]
The fishing pole and the hat add a very high skill to your fishing level, making it more cost effective of getting 950 fishing.

**Comment by unknowndev** [comment]
The Fishing Pole and Nat's hat are already supported. However, The bot currently prefers to use inventory based lures over the hat and rod. You have to remove all inventory based lures if you want it to work. (And also not loot them while fishing). I intend to give the user the option to pick ordering at some point which you can track here: https://github.com/unknowndev/CoolFish/issues/24
