### ISSUE TITLE
Unhandled error has occurred on another thread. This may cause an unstable state of the application. 

### ISSUE THREAD

**Issue by Inyri** [unknowndev/CoolFish#58]
Hi,

I just report a recursive error (approximately every 15 minutes) during the operation of the soft :

<code>
[05/16/15 11:59:03.7078 AM] [ERROR] Unhandled error has occurred on another thread. This may cause an unstable state of the application. 
System.AggregateException: Aucune exception de tâche n'a été observée en attendant la tâche ou en accédant à sa propriété Exception. Par conséquent, l'exception non prise en charge a été à nouveau levée par le thread finaliseur. ---> 
</code>

Any fix ?

Regards

**Comment by Ibglitrbug** [comment]
having the same problem every few seconds​

*Anyone can be a Pawn. But it takes a true ?itch to be a Queen.*

**Comment by unknowndev** [comment]
Yep. This is expected. I'm shutting down CoolFish. It should continue to work until a new WoW patch. (I realize the spam could be annoying.
